language: php
php:
  - 7.1

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --filter="DescribeRegion"

branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"

notifications:
  email: false
  slack:
    secure: "mmWiYonRG4/1qicezJxJ03TGLpSmKfeimocYnz6jYMsI2ezuHXd2vJt05BBuThOcdAN+jLNl+5vAOuOMD6QRX1sDTxyNytud404VEqoMhBfVoVjBmVGEag1BEg6W9eraTOU8lWR9BgKyocg/tyVLME/4pZKFOq9l/u4QCZjdR4n1J1qxskyp52+AFzhJ1K430ZS+0kHa8nz7bnWCNd4QPNZ3Cx01GaP6dxCC12Ph5oWvhQmRw7SYrDECeG1h+YOAoUhVFHWhbGs5V06LDkngXAPK5Y2DYBY+tYXrNBrV0DoXQTgB6X4cNDHvthG6iol7V3+0ZMSn2xozXbjJd2jOgSs5HzW6MziS3X5AQpu3MGDfSw0ynlVjO+7B+UjNYtyL+FShY/uHcBOrQpdAewKbsYLOB9S7DulvyWHJ5wirCGacU19mFRG/dcz76gPy1NHGA02REqb1+++IGiXhiZEZPbgWfiHee7EnsxkSx57mRUD+iEFEfUmfmkFYPfkD7b4cq1iqFSAUVqqCccJMjksZ2t31d0ft5gr8CPrZ1Ye4x16wd1cwuK6evoRsgfFw9m4BcM9J5I2bIwuxHcv/nSoxTnw+Bsa8GHBm8sodbbevo1Tdi1K/DFo8O9hTcaJ8FCak3L5HD786ak6/CSmRktaIEsqGATKdKi4y8rVHrb8DHeM="
